#!/bin/bash

# shellcheck source=/dev/null
source /etc/update-motd.d/colors.txt

AVAIL="$(df --output=avail -h / | tail -1 | xargs)"
USED="$(df --output=used -h / | tail -1 | xargs)"
TOTAL="$(df --output=size -h / | tail -1 | xargs)"

used_num="${USED%%[!0-9.]*}"
used_unit="${USED##*[0-9.]}"
avail_num="${AVAIL%%[!0-9.]*}"
avail_unit="${AVAIL##*[0-9.]}"
total_num="${TOTAL%%[!0-9.]*}"
total_unit="${TOTAL##*[0-9.]}"

echo -e " ${TITLE_COLOR}Disk................:${NC} Used: ${TEXT_COLOR}${used_num}${NC} ${used_unit}B | Free: ${TEXT_COLOR}${avail_num}${NC} ${avail_unit}B | Total: ${TEXT_COLOR}${total_num}${NC} ${total_unit}B"
