#!/bin/bash

COLORS_FILE="${MOTD_COLORS_FILE:-/etc/update-motd.d/colors.txt}"
# shellcheck source=/dev/null
[[ -r "$COLORS_FILE" ]] && source "$COLORS_FILE"

processes="$(ps -e --no-headers 2>/dev/null | wc -l | tr -d ' ')"
echo -e " ${TITLE_COLOR}Processes...........:${NC} ${TEXT_COLOR}${processes}${DEFAULT_COLOR} processes"
